[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read", path = "../snapshots" }]

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/contracts/",
    "forge-std/=dependencies/forge-std/src/",
    "ds-test/=dependencies/ds-test/src/"
]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"

[rpc_endpoints]
nebula_testnet = "https://testnet.skalenodes.com/v1/lanky-ill-funny-testnet"
nebula_mainnet = "https://mainnet.skalenodes.com/v1/green-giddy-denebola"